// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsbzN8snLVDuvYo-8ModwKfPxpMVozbmc',
    appId: '1:1075139823517:web:b0122e8966e53fc11cd174',
    messagingSenderId: '1075139823517',
    projectId: 'my-fav-space',
    authDomain: 'my-fav-space.firebaseapp.com',
    storageBucket: 'my-fav-space.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxiO5czLaeNuuw55ccDLDUsrkhaBw7up0',
    appId: '1:1075139823517:android:1c8632a01a977fb31cd174',
    messagingSenderId: '1075139823517',
    projectId: 'my-fav-space',
    storageBucket: 'my-fav-space.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzikqTmvvsIQ6wKW_NwQqLboowc27-ubQ',
    appId: '1:1075139823517:ios:487261fbb42fcd831cd174',
    messagingSenderId: '1075139823517',
    projectId: 'my-fav-space',
    storageBucket: 'my-fav-space.appspot.com',
    iosBundleId: 'com.example.someSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzikqTmvvsIQ6wKW_NwQqLboowc27-ubQ',
    appId: '1:1075139823517:ios:03b22b81d0be21db1cd174',
    messagingSenderId: '1075139823517',
    projectId: 'my-fav-space',
    storageBucket: 'my-fav-space.appspot.com',
    iosBundleId: 'com.example.someSpace.RunnerTests',
  );
}
